name: Slides CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Deploy to GitHub Pages
      uses: ralexander-phi/marp-action@1.0.0
      env: 
        MARP_ARGS: "slides/main.md -o index.html"

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PUBLISH_TO_BRANCH: gh-pages
        BASE_URL: https://piraces.github.io/bicep-demo/